pipeline:
  identifier: Build_huskerd911_hello_dotnet_core_1701277982659
  name: Build hello-dotnet-core
  orgIdentifier: default
  projectIdentifier: hellodevproject
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github
        repoName: huskerd911/hello-dotnet-core
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  identifier: build_dotnet_app
                  name: Build DotNet App
                  spec:
                    shell: Sh
                    command: |-
                      echo "Welcome to Harness CI"
                      dotnet restore
                      dotnet build --no-restore
                      dotnet test --no-build --verbosity normal
          platform:
            arch: Amd64
            os: Linux
          runtime:
            spec: {}
            type: Cloud
        type: CI
